import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Unbounded, Nunito_Sans } from 'next/font/google';
import Header from './_components/header';
import './globals.css';

const lato = localFont({
  variable: '--font-family',
  display: 'swap',
  src: [
    {
      path: './_vendor/fonts/lato-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './_vendor/fonts/lato-medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './_vendor/fonts/lato-semibold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './_vendor/fonts/lato-bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './_vendor/fonts/lato-bolditalic.woff2',
      weight: '700',
      style: 'italic',
    },

    {
      path: './_vendor/fonts/lato-black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
});

const unbounded = Unbounded({
  variable: '--second-family',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600'],
});

const nunitoSans = Nunito_Sans({
  variable: '--third-family',
  subsets: ['latin', 'cyrillic'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${lato.variable} ${unbounded.variable} ${nunitoSans.variable} `}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
